function imdb = getPascal11Imdb(opts) 
% GETPASCAL11IMDB - load Pascal 2011 Imdb file

  dataDir = fullfile(opts.dataOpts.root, 'pascal11') ;
  imdb = vocSetup('dataDir', dataDir, ...
    'edition', opts.dataOpts.vocEdition, ...
    'includeTest', opts.dataOpts.includeTest, ...
    'includeSegmentation', opts.dataOpts.includeSegmentation, ...
    'includeDetection', opts.dataOpts.includeDetection) ;

  if opts.dataOpts.vocAdditionalSegmentations
    imdb = vocSetupAdditionalSegmentations(imdb, 'dataDir', opts.dataDir) ;
  end
